apiVersion: v1
name: nirvati-registry
version: 1.0.3-dev
appVersion: dev
description: A customized container registry for Nirvati
keywords:
- docker
- registry
home: https://nirvati.de
sources:
- https://github.com/nirvati/nirvati-registry
- https://github.com/nirvati/nirvati-registry-helm
maintainers:
- name: Aaron Dewes
  email: aaron@nirvati.org
engine: gotpl
