apiVersion: v1
name: nirvati-registry
version: 1.4.0-dev
appVersion: dev
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
home: https://nirvati.de
sources:
- https://github.com/nirvati/nirvati-registry
- https://github.com/nirvati/nirvati-registry-helm
maintainers:
- name: Aaron Dewes
  email: aaron@nirvati.org
engine: gotpl
